### ISSUE TITLE
Semesters & Modules

### ISSUE THREAD

**Issue by Na-Nazhou** [Na-Nazhou/CosMaS#10]
- [x] GET /semesters/new
- [x] POST /semesters
- [x] PUT /semesters/:name
- [x] DELETE /semesters/:name

- [x] GET /modules/new
- [x] POST /modules
- [x] PUT /modules/:module_code
- [x] DELETE /modules/:module_code

**Comment by Na-Nazhou** [comment]
Improve form 
- [x] explain semester name
- [x] caution update module code

**Comment by Na-Nazhou** [comment]
Additional checks
- [x] Non overlapping intervals
