### ISSUE TITLE
Users

### ISSUE THREAD

**Issue by Na-Nazhou** [Na-Nazhou/CosMaS#2]
- [x] GET /login
- [x] POST /login
- [x] GET /logout
- [x] GET /signup
- [x] POST /signup
- [x] GET /users
- [x] DELETE /users/:id
- [x] GET /users/:id/edit
- [x] PUT /users/:id
- [x] Refine forms, display error messages
- [ ] Allow edit user ID (only implement if have time)
