### ISSUE TITLE
Permissions: users, modules, semesters, courses

### ISSUE THREAD

**Issue by Na-Nazhou** [Na-Nazhou/CosMaS#30]
Users
- [x] Anyone can C and U users
- [x] Only admin can D users
- [x] Admin can U any user
- [x] Normal users can only U himself

Modules & Semesters
- [x] Only admin can CUD modules and semesters 

Courses
- [x] Only admin can CUD courses
- [x] Professor can U a course if he is a professor in that course
